Change jit.c, template.c, write _PyJit_Combine, jit_switch generation.
Squashed commit of the following:

commit 0e03af415377783afdc86a4662e88c6fa1da85fc
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Fri Jun 21 07:29:17 2024 -0500

    More tidying

commit dd836b8d84c3bf5d7be2869516ebf2580cf04910
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Thu Jun 20 21:20:58 2024 -0500

    Cleanup

commit 7fa38d7f6a08c8a9baa174c35942186b44cfc3df
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Thu Jun 20 15:04:17 2024 -0500

    Manually unroll the loop

commit 5eb5cbdd921f6ea800b6622f3159a79b33e1d635
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Thu Jun 20 10:25:35 2024 -0500

    Reintroduce _JIT_LENGTH

commit 0c34c51f08740cfe0199119605158d357bf33687
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Thu Jun 20 10:08:15 2024 -0500

    Don't include stdio.h in jit templates

commit e901a0deebffe1b4cd6a11bb0b5478a6b94a2031
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Thu Jun 20 09:59:59 2024 -0500

    Fix issues in _PyJit_Combine; stencils are huge!

commit 5af5e6d6734c4704b66012356af46954de7f12da
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Wed Jun 19 17:04:44 2024 -0500

    Tweak debug printing. Many segfaults but...

commit 558db16df4bf4b4fa7763d827624fe15a454aa5a
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Wed Jun 19 15:09:21 2024 -0500

    Fix template.c to build superinstructions

    Also no need to pass _JIT_LENGTH anymore

commit f68ed9c766a752daba48c05071b01dd6940606d7
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Wed Jun 19 15:06:58 2024 -0500

    Minor formatting in jit.c

commit 79c5be41f78719912a941f45847b879de442e2bb
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Wed Jun 19 12:09:44 2024 -0500

    Assertion EMPTY() failed... need to figure out stack effects?

commit 91ea2549d54aa88f5d3a52fe404da87e4f4bb109
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Wed Jun 19 12:03:35 2024 -0500

    Fix some errors in jit.c flags, Properties.from_list

commit 68cb9aee40067baee2ecbd85120ef9d30225e429
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Wed Jun 19 10:53:33 2024 -0500

    Some formatting

commit 6f2c14395f390dbdbb6da23e0141ed690b076c7e
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Wed Jun 19 10:44:58 2024 -0500

    Seemingly working, removed oparg assert... are the stencils correct?

commit 994246bae5741d65147f4230031f991098d88d9a
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Wed Jun 19 10:26:47 2024 -0500

    Building nodes properly, but...

    --Instructions like _LOAD_FAST_0 (and the remainder of the family) are getting confused because they don't USE the oparg, but the oparg is still set interally, so some o
    f the assertions fail

commit 4681e23a52323f8e27b0c91703e40b9370ac898e
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Wed Jun 19 08:56:04 2024 -0500

    Emit HAS_OPERAND_FLAG

commit a92e884cf5ae84b8db002cf4ef9faa27e1d5d074
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Wed Jun 19 08:38:00 2024 -0500

    Rephrase analyzer to use 'conflict' instead of 'compatibile'

commit 422086129b8b0c36a902655f659c5731972a3995
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Tue Jun 18 15:26:23 2024 -0500

    Some more tweaks, specially in template.c, trying to get the JIT stencils to actually compile together again

commit e3a11a8986ae9fd5952d997174b517bc8062ecc2
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Tue Jun 18 14:51:07 2024 -0500

    Actually builds???

commit d571bc91521f62cda42719585e2ce5ccc7ff2e6b
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Tue Jun 18 14:43:31 2024 -0500

    Can't end supernodes.c with a comment?

commit dccd7b1cc9a9a3802e24aab7fe803ea9499ebe1e
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Tue Jun 18 12:17:07 2024 -0500

    Add switch_generator to regen-jit

commit 810ae4ac8f9a946ced918a60496a64ed27a88d2e
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Tue Jun 18 10:55:30 2024 -0500

    Building with targets, still segfaulting on combine

commit cd45971dc1eb7b6904707eaf8c6b1144f4817d77
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Tue Jun 18 08:37:54 2024 -0500

    Need to figure out what .format is

commit 835a542a1773e2a296e31476e251224ba0c69b33
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Tue Jun 18 07:32:14 2024 -0500

    Building but segfaulting! Hooray!

commit cd1e6554d852763ee8d1399722cd61fbf714518c
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Mon Jun 17 16:44:20 2024 -0500

    More work, undefined reference to _JIT_INDEX in jit.o...

commit aae51064a96252cb689a631b194efe4dcae5b89e
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Mon Jun 17 15:02:34 2024 -0500

    start writing _PyJIT_Combine

commit 0144935fff51a3a0d52a8e720de5560cde488e1d
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Mon Jun 17 12:39:35 2024 -0500

    Basic machinery, but _JIT_INDEX needs to return _PyUOpInstruction

commit d20de151e8b7be9948b2d0278d3e579c0da08130
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Mon Jun 17 12:11:33 2024 -0500

    Change _JIT_INDEX to take a pointer instead of vars

commit 4cc9ca53c057b2962a3e76b0ae607370a445d8a0
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Mon Jun 17 12:04:01 2024 -0500

    Include jit_switch.h

commit cbbafbb9696eca87c4d8b267256a8c28eb7fee92
Author: Jeff Glass <glass.jeffrey@gmail.com>
Date:   Mon Jun 17 12:03:18 2024 -0500

    jit_switch_generator defines #MAX_SUPERNODE_DEPTH